# Generated by Django 4.1.5 on 2023-04-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=225)),
                ('tutor_for_session', models.CharField(max_length=50)),
                ('student', models.CharField(max_length=225)),
            ],
        ),
    ]
