# Generated by Django 4.1.5 on 2023-04-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_session_request_left_feedback_tutor_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='usernm',
            field=models.CharField(default='No session approved yet', max_length=255),
        ),
    ]
