# Generated by Django 4.1.7 on 2023-04-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_studentprofile_tutorsession_remove_tutorclass_tutor_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="StudentProfile",),
    ]
