# Generated by Django 4.1.5 on 2023-04-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_session_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_request',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
