# Generated by Django 4.1.7 on 2023-04-17 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_tutorsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes_with_tutors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=225)),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tutorclass')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('computing_id', models.CharField(max_length=8)),
                ('classes', models.ManyToManyField(blank=True, related_name='tutors', to='myapp.tutorclass')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='TutorSession',
        ),
        migrations.AlterField(
            model_name='tutorclass',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tutor'),
        ),
    ]
