# Generated by Django 4.1.5 on 2023-04-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_session_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorclass',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
