# Generated by Django 4.1.7 on 2023-04-17 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_classes_with_tutors_tutor_delete_tutorsession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='computing_id',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='last_name',
        ),
    ]
