# Generated by Django 4.1.7 on 2023-04-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_delete_studentprofile"),
    ]

    operations = [
        migrations.DeleteModel(name="TutorSession",),
    ]
