# Generated by Django 3.2.17 on 2023-04-19 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tutorclass_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
