# Generated by Django 4.1.7 on 2023-04-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_delete_tutorsession"),
    ]

    operations = [
        migrations.DeleteModel(name="TutorRequest",),
    ]
