# Generated by Django 4.1.7 on 2023-04-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_tutorclass_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorclass",
            name="days",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tutorclass",
            name="tutoring_type",
            field=models.CharField(
                choices=[("online", "Online"), ("in_person", "In Person")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
