# Generated by Django 3.2.17 on 2023-04-20 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20230419_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='email',
        ),
        migrations.AddField(
            model_name='session_request',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
