# Generated by Django 4.1.5 on 2023-04-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20230416_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorclass',
            name='tutor',
            field=models.CharField(max_length=255),
        ),
    ]
