# Generated by Django 4.1.7 on 2023-04-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_tutor_tutorclass_tutor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorclass',
            old_name='tutor_id',
            new_name='tutor',
        ),
    ]
