# Generated by Django 4.1.5 on 2023-04-17 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_tutorclass_tutor'),
        ('myapp', '0007_rename_tutor_id_tutorclass_tutor'),
    ]

    operations = [
    ]
