# Generated by Django 4.1.7 on 2023-04-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_merge_20230417_2231"),
        ("myapp", "0008_merge_20230417_2238"),
    ]

    operations = []
