# Generated by Django 4.1.7 on 2023-04-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_merge_20230417_2244"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorclass",
            name="tutor",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
